# Build settings
markdown:           kramdown
permalink:          pretty


# Dependencies
markdown:           kramdown
highlighter:        rouge
plugins:            [jekyll-paginate]

# Permalinks
permalink:          pretty

# Setup
title:              "English 101/ALP(099)"
tagline:
description:        "Pierce College|W19"
host:               127.0.0.1
url:                ""
baseurl:            "/e101v1"
email:              jloan@pierce.ctc.edu


paginate:           5
layout:             blog-post

# Custom vars
version:            2.0.0
